export default {
  name: "La Falsa Facilidad",
  words: [
    { id: 1, ru: "здоровый", es: "sano" },
    { id: 2, ru: "следующий", es: "siguiente" },
    { id: 3, ru: "новичок", es: "el principiante" },
    { id: 4, ru: "начать", es: "comenzar" },
    { id: 5, ru: "плавный", es: "suave" },
    { id: 6, ru: "плавно", es: "suavemente" },
    { id: 7, ru: "рука (целиком)", es: "el brazo" },
    { id: 8, ru: "глубокий", es: "profundo" },
    { id: 9, ru: "растягивать", es: "estirar" },
    { id: 10, ru: "боль", es: "el dolor" },
    { id: 11, ru: "пот", es: "el sudor" },
    { id: 12, ru: "рука", es: "la mano" },
    { id: 13, ru: "нога", es: "la pierna" },
    { id: 14, ru: "локоть", es: "el codo" },
    { id: 15, ru: "живот", es: "el estómago" },
    { id: 16, ru: "спина", es: "la espalda" },
    { id: 17, ru: "плечо", es: "el hombro" },
    { id: 18, ru: "позвоночник", es: "la columna vertebral" },
    { id: 19, ru: "лоб", es: "la frente" },
    { id: 20, ru: "сгибать", es: "doblar" },
    { id: 21, ru: "вернуться", es: "regresar" },
    { id: 22, ru: "поддерживать, держать", es: "mantener" },
    { id: 23, ru: "упражнение", es: "el ejercicio" },
    { id: 24, ru: "реклама", es: "el anuncio" },
    { id: 25, ru: "тело, туловище", es: "el cuerpo" },
    { id: 26, ru: "голова", es: "la cabeza" },
    { id: 27, ru: "шея", es: "el cuello" },
    { id: 28, ru: "попытаться", es: "intentar" },
    { id: 29, ru: "колено", es: "la rodilla" },
    { id: 30, ru: "гибкость", es: "la flexibilidad" }
  ]
};
